# Generated by Django 5.1.7 on 2025-03-25 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50, verbose_name='Nombre de Usuario')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre Completo')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.area', verbose_name='Área')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicaciones.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre_completo'],
            },
        ),
    ]
