# Generated by Django 5.1.7 on 2025-03-25 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('ubicaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(verbose_name='Fecha de Asignación')),
                ('fecha_devolucion', models.DateField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('motivo_asignacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de Asignación')),
                ('estado_asignacion', models.CharField(choices=[('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('asignado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_realizadas', to='usuarios.usuario', verbose_name='Asignado Por')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipos.equipo', verbose_name='Equipo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asignación de Equipo',
                'verbose_name_plural': 'Asignaciones de Equipos',
                'ordering': ['-fecha_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='ConexionRed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_conexion', models.CharField(max_length=20, verbose_name='Tipo de Conexión')),
                ('ip_publica', models.CharField(blank=True, max_length=20, null=True, verbose_name='IP Pública')),
                ('ip_privada', models.CharField(max_length=20, verbose_name='IP Privada')),
                ('mascara_subred', models.CharField(blank=True, max_length=20, null=True, verbose_name='Máscara de Subred')),
                ('gateway', models.CharField(blank=True, max_length=20, null=True, verbose_name='Gateway')),
                ('dns_primario', models.CharField(blank=True, max_length=20, null=True, verbose_name='DNS Primario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Conexión de Red',
                'verbose_name_plural': 'Conexiones de Red',
                'ordering': ['equipo'],
            },
        ),
        migrations.CreateModel(
            name='HistorialUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField(verbose_name='Fecha de Cambio')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipos.equipo', verbose_name='Equipo')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.usuario', verbose_name='Registrado Por')),
                ('ubicacion_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_origen', to='ubicaciones.ubicacion', verbose_name='Ubicación Anterior')),
                ('ubicacion_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_como_destino', to='ubicaciones.ubicacion', verbose_name='Ubicación Nueva')),
            ],
            options={
                'verbose_name': 'Historial de Ubicación',
                'verbose_name_plural': 'Historiales de Ubicaciones',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
