# Generated by Django 5.1.7 on 2025-03-25 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('proveedor', models.CharField(max_length=100, verbose_name='Proveedor')),
                ('condiciones', models.TextField(blank=True, null=True, verbose_name='Condiciones')),
                ('documento_referencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Documento de Referencia')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Finalización')),
                ('tipo', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('responsable', models.CharField(max_length=100, verbose_name='Responsable')),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo')),
                ('resultado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('PENDIENTE', 'Pendiente'), ('FALLIDO', 'Fallido')], max_length=20, verbose_name='Resultado')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
