# Generated by Django 5.1.7 on 2025-03-25 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('compatibilidad', models.TextField(blank=True, null=True, verbose_name='Compatibilidad')),
                ('cantidad_disponible', models.IntegerField(verbose_name='Cantidad Disponible')),
                ('cantidad_minima', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Mínima')),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Costo Unitario')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fabricante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipos.fabricante', verbose_name='Fabricante')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubicaciones.ubicacion', verbose_name='Ubicación')),
            ],
            options={
                'verbose_name': 'Consumible',
                'verbose_name_plural': 'Consumibles',
                'ordering': ['tipo', 'modelo'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consumo', models.DateField(verbose_name='Fecha de Consumo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('solicitado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Solicitado Por')),
                ('autorizado_por', models.CharField(blank=True, max_length=100, null=True, verbose_name='Autorizado Por')),
                ('motivo', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo')),
                ('consumible', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consumibles.consumible', verbose_name='Consumible')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Consumo Histórico',
                'verbose_name_plural': 'Consumos Históricos',
                'ordering': ['-fecha_consumo'],
            },
        ),
        migrations.CreateModel(
            name='ConsumibleEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sugerida_mes', models.IntegerField(blank=True, null=True, verbose_name='Cantidad Sugerida por Mes')),
                ('rendimiento_paginas', models.IntegerField(blank=True, null=True, verbose_name='Rendimiento en Páginas')),
                ('consumible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumibles.consumible', verbose_name='Consumible')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Consumible por Equipo',
                'verbose_name_plural': 'Consumibles por Equipos',
                'unique_together': {('consumible', 'equipo')},
            },
        ),
    ]
